;(sqrt(abs(exp(a)+(sinh(b)*tanh(c)))))
;(defun arithmatic (a b c)
;(sqrt (abs (+ (exp a) (* (sinh b) (tanh c)))))
;)
(setq pi 3.14)
(write pi)
(terpri)
(write "Enter value of a")
(setq a (read))
(terpri)
(write "Enter value of b")
(setq b (read))
;(write (cos pi))
(terpri)
(write "Enter value of c")
(setq c (read))
(setq result (sqrt (abs (+ (exp a) (* (sinh b) (tanh c))))))
(write result)