;code to generate random numbers of square matrix and calculate det()
(defun matrix (n)
	(setf x (make-array '(n n)))
		(dotimes (i n)
			(dotimes (j n)
				(setf (aref x i j ) (* i j))
			)
		)
)
(write "Enter matrix")
(setq a (read))
(write (matrix a))